import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { reports, users } from './data'
import type { DownloadEntry, UserProfile, UserRole } from './types'
import './App.css'

const SESSION_STORAGE_KEY = 'reports-ui-session'
const DOWNLOAD_STORAGE_KEY = 'reports-ui-download-history'

const roleLabels: Record<UserRole, string> = {
  operations: 'Operations',
  'central-ops': 'Central Ops',
  insurance: 'Insurance',
  finance: 'Finance',
}

const categoryLabels = {
  operations: 'Operations',
  collections: 'Collections',
  compliance: 'Compliance',
  finance: 'Finance',
}

function App() {
  const [sessionUser, setSessionUser] = useState<UserProfile | null>(() => {
    const session = localStorage.getItem(SESSION_STORAGE_KEY)
    return session ? (JSON.parse(session) as UserProfile) : null
  })
  const [history, setHistory] = useState<DownloadEntry[]>(() => {
    const rawHistory = localStorage.getItem(DOWNLOAD_STORAGE_KEY)
    return rawHistory ? (JSON.parse(rawHistory) as DownloadEntry[]) : []
  })
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [search, setSearch] = useState('')
  const [downloadingReportId, setDownloadingReportId] = useState<string | null>(null)

  const availableReports = useMemo(() => {
    if (!sessionUser) {
      return []
    }

    const term = search.trim().toLowerCase()
    return reports
      .filter((report) => report.allowedRoles.includes(sessionUser.role))
      .filter((report) => {
        if (!term) {
          return true
        }
        return (
          report.name.toLowerCase().includes(term) ||
          report.description.toLowerCase().includes(term) ||
          report.category.toLowerCase().includes(term)
        )
      })
  }, [search, sessionUser])

  const login = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    const matchedUser = users.find(
      (candidate) =>
        candidate.username === username.trim().toLowerCase() && candidate.password === password,
    )

    if (!matchedUser) {
      setError('Invalid username or password.')
      return
    }

    const profile: UserProfile = {
      id: matchedUser.id,
      name: matchedUser.name,
      email: matchedUser.email,
      role: matchedUser.role,
    }
    setSessionUser(profile)
    localStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(profile))
    setError('')
    setUsername('')
    setPassword('')
  }

  const logout = () => {
    setSessionUser(null)
    localStorage.removeItem(SESSION_STORAGE_KEY)
    setSearch('')
  }

  const downloadReport = async (reportId: string) => {
    if (!sessionUser) {
      return
    }
    const report = reports.find((item) => item.id === reportId)
    if (!report) {
      return
    }

    setDownloadingReportId(reportId)
    await new Promise((resolve) => setTimeout(resolve, 600))

    const time = new Date()
    const timestamp = time.getTime()
    const csvContent = [
      `Report Name,${report.name}`,
      `Generated By,${sessionUser.name}`,
      `Role,${roleLabels[sessionUser.role]}`,
      `Generated At,${time.toISOString()}`,
      '',
      'Sample Data Row',
      'This is a placeholder file,connect this flow to backend API.',
    ].join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const fileUrl = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = fileUrl
    link.download = `${report.name.replaceAll(/\s+/g, '-').toLowerCase()}-${timestamp}.csv`
    document.body.append(link)
    link.click()
    link.remove()
    URL.revokeObjectURL(fileUrl)

    const newEntry: DownloadEntry = {
      id: `dl-${timestamp}`,
      reportId: report.id,
      reportName: report.name,
      downloadedAt: time.toISOString(),
      by: sessionUser.name,
    }

    const updatedHistory = [newEntry, ...history].slice(0, 12)
    setHistory(updatedHistory)
    localStorage.setItem(DOWNLOAD_STORAGE_KEY, JSON.stringify(updatedHistory))
    setDownloadingReportId(null)
  }

  if (!sessionUser) {
    return (
      <main className="shell login-shell">
        <div className="login-atmosphere" aria-hidden="true">
          <div className="login-orb login-orb--a" />
          <div className="login-orb login-orb--b" />
          <div className="login-orb login-orb--c" />
          <div className="login-mesh" />
          <div className="login-shine" />
        </div>

        <section className="login-card">
          <div className="login-card-accent" aria-hidden="true" />
          <div className="login-card-inner">
            <header className="login-brand">
              <div className="login-mark" aria-hidden="true">
                <svg viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <rect x="6" y="22" width="7" height="12" rx="1.5" fill="currentColor" opacity="0.35" />
                  <rect x="16.5" y="14" width="7" height="20" rx="1.5" fill="currentColor" opacity="0.55" />
                  <rect x="27" y="8" width="7" height="26" rx="1.5" fill="currentColor" />
                </svg>
              </div>
              <h1>Reporting Portal</h1>
              <p className="login-tagline">
                Sign in to access reports tailored to your role.
              </p>
            </header>

            <form className="login-form" onSubmit={login}>
              <label>
                Username
                <input
                  type="text"
                  value={username}
                  placeholder="Enter your username"
                  autoComplete="username"
                  onChange={(event) => setUsername(event.target.value)}
                  required
                />
              </label>
              <label>
                Password
                <input
                  type="password"
                  value={password}
                  placeholder="Enter your password"
                  autoComplete="current-password"
                  onChange={(event) => setPassword(event.target.value)}
                  required
                />
              </label>
              {error ? <p className="error-text">{error}</p> : null}
              <button className="login-submit-btn" type="submit">
                Sign in
              </button>
            </form>

            <p className="login-footnote">Use your organization credentials.</p>
          </div>
        </section>
      </main>
    )
  }

  const roleScopedHistory = history.filter((item) => item.by === sessionUser.name)

  return (
    <main className="shell dashboard-shell">
      <section className="glass-panel dashboard-panel">
        <header className="dashboard-header">
          <div>
            <p className="eyebrow">Welcome back</p>
            <h2>{sessionUser.name}</h2>
            <p className="subtitle">
              {roleLabels[sessionUser.role]} Team • {sessionUser.email}
            </p>
          </div>
          <button className="secondary-btn" type="button" onClick={logout}>
            Logout
          </button>
        </header>

        <section className="stats-grid">
          <article>
            <p>Accessible Reports</p>
            <strong>{availableReports.length}</strong>
          </article>
          <article>
            <p>Downloads (This User)</p>
            <strong>{roleScopedHistory.length}</strong>
          </article>
          <article>
            <p>Primary Domain</p>
            <strong>{roleLabels[sessionUser.role]}</strong>
          </article>
        </section>

        <section className="toolbar">
          <label>
            Search reports
            <input
              type="search"
              value={search}
              placeholder="Outstanding, Collection, Disbursement..."
              onChange={(event) => setSearch(event.target.value)}
            />
          </label>
        </section>

        <section className="reports-list-panel">
          <div className="reports-list-header">
            <h3>Available Reports</h3>
          </div>
          {availableReports.length === 0 ? (
            <article className="empty-state">
              <h3>No matching reports</h3>
              <p>Try a different search term to discover accessible reports.</p>
            </article>
          ) : (
            <div className="reports-list-wrap">
              <table className="reports-list">
                <thead>
                  <tr>
                    <th>Report</th>
                    <th>Category</th>
                    <th>Cadence</th>
                    <th>Format</th>
                    <th aria-label="Download action"></th>
                  </tr>
                </thead>
                <tbody>
                  {availableReports.map((report) => (
                    <tr key={report.id}>
                      <td>
                        <strong>{report.name}</strong>
                        <p>{report.description}</p>
                      </td>
                      <td>{categoryLabels[report.category]}</td>
                      <td>{report.cadence}</td>
                      <td>{report.format}</td>
                      <td>
                        <button
                          type="button"
                          onClick={() => void downloadReport(report.id)}
                          disabled={downloadingReportId === report.id}
                        >
                          {downloadingReportId === report.id ? 'Preparing...' : 'Download'}
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>

        <section className="history-panel">
          <h3>Recent Downloads</h3>
          {roleScopedHistory.length === 0 ? (
            <p className="empty-caption">No downloads yet for this user.</p>
          ) : (
            <ul>
              {roleScopedHistory.slice(0, 6).map((entry) => (
                <li key={entry.id}>
                  <span>{entry.reportName}</span>
                  <time>{new Date(entry.downloadedAt).toLocaleString()}</time>
                </li>
              ))}
            </ul>
          )}
        </section>
      </section>
    </main>
  )
}

export default App
