import type { AuthRecord, ReportDefinition } from './types'

export const users: AuthRecord[] = [
  {
    id: 'usr-ops-01',
    username: 'operations.user',
    password: 'Welcome@123',
    name: 'Riya Sharma',
    email: 'riya.sharma@org.com',
    role: 'operations',
  },
  {
    id: 'usr-cops-01',
    username: 'centralops.user',
    password: 'Welcome@123',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@org.com',
    role: 'central-ops',
  },
  {
    id: 'usr-ins-01',
    username: 'insurance.user',
    password: 'Welcome@123',
    name: 'Neha Nair',
    email: 'neha.nair@org.com',
    role: 'insurance',
  },
  {
    id: 'usr-fin-01',
    username: 'finance.user',
    password: 'Welcome@123',
    name: 'Karthik Rao',
    email: 'karthik.rao@org.com',
    role: 'finance',
  },
]

export const reports: ReportDefinition[] = [
  {
    id: 'rpt-outstanding',
    name: 'Outstanding Report',
    description: 'Pending dues bucketed by branch, team and product.',
    category: 'operations',
    cadence: 'Daily',
    format: 'CSV',
    allowedRoles: ['operations', 'central-ops', 'finance'],
  },
  {
    id: 'rpt-overdue',
    name: 'Overdue Report',
    description: 'Aging view of overdue accounts with actionability flags.',
    category: 'collections',
    cadence: 'Daily',
    format: 'CSV',
    allowedRoles: ['operations', 'central-ops', 'finance'],
  },
  {
    id: 'rpt-ftod',
    name: 'FTOD',
    description: 'First-time overdue list with contact and status snapshots.',
    category: 'collections',
    cadence: 'Daily',
    format: 'CSV',
    allowedRoles: ['operations', 'central-ops'],
  },
  {
    id: 'rpt-collection-t',
    name: 'Collection [T]',
    description: 'Intra-day collection movement tracker with target attainment.',
    category: 'collections',
    cadence: 'On Demand',
    format: 'XLSX',
    allowedRoles: ['operations', 'central-ops', 'finance'],
  },
  {
    id: 'rpt-collection-t-1',
    name: 'Collection [T-1]',
    description: 'Day-end collection closure and variance highlights.',
    category: 'collections',
    cadence: 'Daily',
    format: 'XLSX',
    allowedRoles: ['operations', 'central-ops', 'finance'],
  },
  {
    id: 'rpt-disbursement',
    name: 'Disbursement',
    description: 'Daily disbursement register with channel and product split.',
    category: 'finance',
    cadence: 'Daily',
    format: 'XLSX',
    allowedRoles: ['finance', 'central-ops'],
  },
  {
    id: 'rpt-insurance-renewal',
    name: 'Insurance Renewal Tracker',
    description: 'Upcoming policy renewals, premium flags and claim blockers.',
    category: 'compliance',
    cadence: 'Weekly',
    format: 'PDF',
    allowedRoles: ['insurance', 'central-ops'],
  },
]
